#include "examples.hpp"

#include "passes.hpp"

#include <set>
#include <sstream>

namespace perm {

namespace {

struct Sample {
    const char* pass;
    const char* code; // a function named f
    std::vector<int> show; // which candidates to show (indexes into the pass's output)
};

// One small function per pass, written so the shown candidates are the typical
// rewrites. docs/passes.md is generated from these (--pass-examples), and a
// unit test checks it is up to date.
const std::vector<Sample>& samples() {
    static const std::vector<Sample> s = {
        {"reorder_saves", R"(void Group::f(int idx)
{
    Weapon* a = leader->weapon;
    Weapon* b = list[idx]->weapon;
    Weapon* c = leader->weapon2;
    leader->Copy(list[idx]);
})", {0, 4}},
        {"move_stmt", R"(void f(Ped* p)
{
    p->a = 1;
    p->b = 2;
    g();
})", {0}},
        {"inline_local", R"(void f(Ped* p)
{
    Car* car = p->car;
    car->speed = 0;
})", {0, 1}},
        {"sink_decl", R"(void f(int n)
{
    int i;
    g();
    if (n)
    {
        i = 2;
        h(i);
    }
})", {0}},
        {"hoist_decl", R"(void f(int n)
{
    g();
    if (n)
    {
        int i = 2;
        h(i);
    }
})", {0}},
        {"merge_decl", R"(void f(int n)
{
    int i;
    g();
    i = n * 2;
    h(i);
})", {0}},
        {"swap_operands", R"(int f(Ped* p)
{
    return p->a + p->b;
})", {0}},
        {"flip_compare", R"(void f(Ped* p)
{
    if (p->a < p->b)
        g();
})", {0}},
        {"invert_if", R"(void f(Ped* p)
{
    if (p->a == 0)
        g();
    else
        h();
})", {0}},
        {"ternary", R"(void f(Ped* p, int x)
{
    p->a = x > 0 ? 1 : 2;
})", {0}},
        {"compound_assign", R"(void f(Ped* p, int x)
{
    p->a = p->a + x;
})", {0}},
        {"bool_return", R"(bool f(Ped* p)
{
    return p->a <= p->b;
})", {0, 3}},
        {"ternary_arg", R"(void f(Ped* p)
{
    p->Set(p->state == 0 ? 1 : 0);
})", {0}},
        {"switch_if", R"(void f(Ped* p, int notify)
{
    if (notify == 1)
    {
        g(p->a);
    }
})", {0}},
        {"early_return", R"(int f(Ped* p)
{
    if (!p)
    {
        return 0;
    }
    else
    {
        g(p);
    }
    return 1;
})", {0}},
        {"branch_dup", R"(void f(Ped* p)
{
    if (p->a)
    {
        g(1);
    }
    else
    {
        g(2);
    }
    p->c = 5;
})", {0}},
        {"cond_split", R"(void f(Ped* p)
{
    if (p->a && p->b)
        g();
})", {0}},
        {"explicit_compare", R"(void f(Ped* p)
{
    if (!p->car)
        g();
})", {0}},
        {"negate_const", R"(int f(int x)
{
    return x - 256;
})", {0}},
        {"loop_form", R"(void f(Ped* p)
{
    for (int i = 0; i < p->count; i++)
    {
        g(i);
    }
})", {0}},
        {"reassociate", R"(int f(Ped* p)
{
    return p->a + p->b + p->c;
})", {0}},
        {"inequalities", R"(void f(Ped* p)
{
    if (p->a > 4)
        g();
})", {0}},
        {"chain_assign", R"(void f(Ped* p)
{
    p->a = 0;
    p->b = 0;
})", {0}},
        {"scope_block", R"(void f(Ped* p)
{
    int x = p->a;
    g(x);
    h();
})", {0}},
        {"local_type", R"(void f(Ped* p)
{
    s32 x = p->a;
    g(x);
})", {0, 4}},
        {"locals_to_array", R"(void f(Ped* p)
{
    s32 x = p->a;
    s32 y = p->b;
    g(x, y);
})", {0}},
        {"reorder_cases", R"(int f(int n)
{
    switch (n)
    {
        case 1:
            return g(1);
        case 2:
            return g(2);
    }
    return 0;
})", {0}},
        {"split_case_labels", R"(int f(int n)
{
    switch (n)
    {
        case 1:
        case 2:
            return g(1);
    }
    return 0;
})", {0}},
        {"use_getter", R"(Fix16 f(Ped* p)
{
    return p->field_1AC_cam.x;
})", {0}},
        {"temp_for_expr", R"(void f(Ped* p)
{
    g((u8)p->a);
})", {0}},
        {"named_op", R"(Fix16 f(Fix16 a, Fix16 b)
{
    return -a * b;
})", {0, 1}},
        {"cast_operand", R"(u32 f(s32 a, u8 b)
{
    return a / b;
})", {0, 6}},
        {"remove_stmt", R"(void f(Ped* p)
{
    g();
    WIP_IMPLEMENTED;
})", {1}},
    };
    return s;
}

// The function's lines, without the signature and braces, for showing.
std::string body(const std::string& f) {
    std::istringstream in(f);
    std::string line, out;
    while (std::getline(in, line)) out += line + "\n";
    return out;
}

} // namespace

std::string passExamplesMarkdown() {
    std::ostringstream o;
    o << "# Passes\n\n"
         "Generated by `cpp_permuter --pass-examples` from the samples in `src/examples.cpp`; "
         "a unit test checks this file is up to date. Each example shows a small function "
         "and what the pass makes of it (some passes offer more candidates than shown). Most "
         "passes also work in the other direction.\n\n";
    // use_getter needs a getter to know about
    setGetters({{"get_cam_x", "field_1AC_cam.x"}});
    // named_op needs to know the named versions of the operators
    setOpAliases({{"*", "Multiply_408680"}, {"neg", "Negate_4086A0"}});
    for (auto& s : samples()) {
        const Pass* p = findPass(s.pass);
        if (!p) continue;
        o << "## `" << s.pass << "`\n\n" << p->description << ".\n\n";
        if (std::string(s.pass) == "use_getter")
            o << "With `Fix16 get_cam_x() { return field_1AC_cam.x; }` in an included header:\n\n";
        if (std::string(s.pass) == "named_op")
            o << "With `--op-alias '*=Multiply_408680' --op-alias neg=Negate_4086A0`:\n\n";
        std::string err;
        auto f = parseFunc(s.code, err);
        std::vector<std::string> outs;
        std::set<std::string> seen;
        if (f)
            p->enumerate(*f, [&](Mutation m) {
                std::string t = m();
                if (!t.empty() && seen.insert(t).second) outs.push_back(t);
                return outs.size() < 100;
            });
        o << "```cpp\n" << body(s.code) << "```\n\n";
        for (int i : s.show) {
            if (i >= (int)outs.size()) {
                o << "(no candidate " << i << ")\n\n";
                continue;
            }
            o << "becomes\n\n```cpp\n" << body(outs[i]) << "```\n\n";
        }
        if (outs.size() > s.show.size())
            o << "(" << outs.size() << " candidates in all for this function.)\n\n";
    }
    setGetters({});
    return o.str();
}

} // namespace perm
